#pragma once

#include "glad/glad.h"
#include "irulan/system/App.h"
#include "irulan/system/Buffer.h"
#include "irulan/system/Resource.h"
#include "irulan/system/ResourceManager.h"
#include "irulan/math/Vector2.h"
#include "irulan/math/Matrix4.h"
#include "irulan/data/Vertex.h"
#include "irulan/data/Mesh.h"
#include "irulan/graph/Descriptor.h"
#include "irulan/graph/Shader.h"
#include "irulan/graph/Texture2D.h"
#include "irulan/graph/Framebuffer.h"